# # How to Extract RGB Color Space ?

In [7]:
import numpy as np
import cv2
img = cv2.imread('players.jfif')


B,G,R = cv2.split(img)

zeros = np.zeros(img.shape[:2], dtype="uint8")
cv2.imshow("Red", cv2.merge([zeros,zeros,R]))
cv2.waitKey(0)
cv2.imshow("Green", cv2.merge([zeros,G,zeros]))
cv2.waitKey(0)
cv2.imshow("Blue", cv2.merge([B,zeros,zeros]))
cv2.waitKey(0)

cv2.destroyAllWindows()

In [3]:
B

array([[122, 122, 122, ..., 128, 128, 128],
       [122, 122, 122, ..., 128, 128, 128],
       [122, 122, 122, ..., 128, 128, 128],
       ...,
       [ 96,  95,  94, ...,  96, 101, 100],
       [ 95,  94,  93, ...,  93,  98, 103],
       [ 95,  94,  93, ...,  91,  95, 105]], dtype=uint8)

In [4]:
R

array([[182, 182, 182, ..., 193, 193, 193],
       [182, 182, 182, ..., 193, 193, 193],
       [182, 182, 182, ..., 193, 193, 193],
       ...,
       [255, 255, 255, ..., 229, 232, 231],
       [255, 255, 254, ..., 226, 229, 234],
       [255, 255, 254, ..., 224, 226, 236]], dtype=uint8)

In [5]:
G

array([[158, 158, 158, ..., 165, 165, 165],
       [158, 158, 158, ..., 165, 165, 165],
       [158, 158, 158, ..., 165, 165, 165],
       ...,
       [207, 206, 205, ..., 176, 179, 178],
       [206, 205, 204, ..., 173, 176, 181],
       [206, 205, 204, ..., 171, 173, 183]], dtype=uint8)

In [6]:
zeros

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)